import "./styles.css";
import "./index.html";
import items from "./utils/generate-posts.js";
console.log(items);
import posts from "./data/posts.json";
console.log(posts);
import item from "./templates/item.hbs";
console.log(item);
const postList = { post: document.querySelector(".post-feed") };
const postItem = item(posts);
console.log(postItem);
// postList.post.append(postItem);
// import Counter from "./plugins/counter";
// import * as basicLightbox from "basiclightbox";
